_parent_: projects/neuralangelo/configs/base.yaml
trainer:
    type: projects.NeuralLumen.trainer
data:
    readjust:
        center:
        - 0.0
        - 0.0
        - 0.0
        scale: 1.0
    root: /ghome/yyang/dataset/rene_dataset/savannah
    train:
        annotation: /ghome/yyang/PycharmProjects/neuralangelo/dataset_rene/savannah/train_transforms.json
        batch_size: 1
        image_size:
        - 270
        - 360
    type: projects.NeuralLumen.data
    val:
        annotation: /ghome/yyang/PycharmProjects/neuralangelo/dataset_rene/savannah/val_transforms.json
        batch_size: 1
        subset: 0
        image_size:
        - 270
        - 360
    bounding_type: "box"   # or "unit_sphere"
    bounding_box_aabb:
        - -0.66
        - -0.516
        - -0.18
        - 0.66
        - 0.42
        - 0.3
model:
    type: projects.NeuralLumen.model
    appear_embed:
        enabled: false
    object:
        sdf:
            encoding:
                coarse2fine:
                    init_active_level: 8
            mlp:
                inside_out: false
    light_visibility:
        enabled: False
        type: sphere_tracing
        visibility_bounding_type: sphere   # or "box"
        visibility_sphere_radius: 0.2
    background:
        enabled: False
    render:
        rand_rays: 2048
    create_semi_sphere: false
